# EURO 2020
#- competition_id: 55
#  season_id: 43
# ESP - 2020/21
#- competition_id: 11
#  season_id: 90
# GER - 2020/21
#- competition_id: 9
#  season_id: 90
# ENG - 2020/21
#- competition_id: 2
#  season_id: 90